
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author erhan
 */
public class todolist extends javax.swing.JFrame {

    /**
     * Creates new form todolist
     */
    public todolist() {
        initComponents();
        m2.setVisible(false);
        m4.setVisible(false);
        m3.setVisible(false);
        m5.setVisible(false);
        d2.setVisible(false);
        d3.setVisible(false);
        d4.setVisible(false);
        d5.setVisible(false);
        c2.setVisible(false);
        c3.setVisible(false);
        c4.setVisible(false);
        c5.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        m5 = new javax.swing.JTextField();
        d2 = new javax.swing.JButton();
        c2 = new javax.swing.JButton();
        c6 = new javax.swing.JButton();
        d3 = new javax.swing.JButton();
        c7 = new javax.swing.JButton();
        c3 = new javax.swing.JButton();
        c8 = new javax.swing.JButton();
        d4 = new javax.swing.JButton();
        c9 = new javax.swing.JButton();
        c4 = new javax.swing.JButton();
        c10 = new javax.swing.JButton();
        d5 = new javax.swing.JButton();
        c5 = new javax.swing.JButton();
        d1 = new javax.swing.JButton();
        c1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        m1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        m3 = new javax.swing.JTextField();
        m4 = new javax.swing.JTextField();
        m2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        m5.setForeground(new java.awt.Color(196, 179, 179));
        m5.setText("5.Mission");
        m5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                m5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                m5FocusLost(evt);
            }
        });
        m5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m5ActionPerformed(evt);
            }
        });

        d2.setBackground(new java.awt.Color(51, 255, 51));
        d2.setText("Done");
        d2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d2ActionPerformed(evt);
            }
        });

        c2.setBackground(new java.awt.Color(255, 51, 51));
        c2.setText("Fail");
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });

        c6.setBackground(new java.awt.Color(204, 204, 204));
        c6.setText("1.Dismis");
        c6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c6ActionPerformed(evt);
            }
        });

        d3.setBackground(new java.awt.Color(51, 255, 51));
        d3.setText("Done");
        d3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d3ActionPerformed(evt);
            }
        });

        c7.setBackground(new java.awt.Color(204, 204, 204));
        c7.setText("2.Dismis");
        c7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c7ActionPerformed(evt);
            }
        });

        c3.setBackground(new java.awt.Color(255, 51, 51));
        c3.setText("Fail");
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });

        c8.setBackground(new java.awt.Color(204, 204, 204));
        c8.setText("3.Dismis");
        c8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c8ActionPerformed(evt);
            }
        });

        d4.setBackground(new java.awt.Color(51, 255, 51));
        d4.setText("Done");
        d4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d4ActionPerformed(evt);
            }
        });

        c9.setBackground(new java.awt.Color(204, 204, 204));
        c9.setText("4.Dismis");
        c9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c9ActionPerformed(evt);
            }
        });

        c4.setBackground(new java.awt.Color(255, 51, 51));
        c4.setText("Fail");
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });

        c10.setBackground(new java.awt.Color(204, 204, 204));
        c10.setText("5.Dismis");
        c10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c10ActionPerformed(evt);
            }
        });

        d5.setBackground(new java.awt.Color(51, 255, 51));
        d5.setText("Done");
        d5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d5ActionPerformed(evt);
            }
        });

        c5.setBackground(new java.awt.Color(255, 51, 51));
        c5.setText("Fail");
        c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5ActionPerformed(evt);
            }
        });

        d1.setBackground(new java.awt.Color(51, 255, 51));
        d1.setText("Done");
        d1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d1ActionPerformed(evt);
            }
        });

        c1.setBackground(new java.awt.Color(255, 51, 51));
        c1.setText("Fail");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });

        jButton3.setText("Close App");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        m1.setForeground(new java.awt.Color(196, 179, 179));
        m1.setText("1.Mission");
        m1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                m1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                m1FocusLost(evt);
            }
        });
        m1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m1ActionPerformed(evt);
            }
        });

        jButton4.setText("Open Mission");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        m3.setForeground(new java.awt.Color(196, 179, 179));
        m3.setText("3.Mission");
        m3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                m3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                m3FocusLost(evt);
            }
        });
        m3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m3ActionPerformed(evt);
            }
        });

        m4.setForeground(new java.awt.Color(196, 179, 179));
        m4.setText("4.Mission");
        m4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                m4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                m4FocusLost(evt);
            }
        });
        m4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m4ActionPerformed(evt);
            }
        });

        m2.setForeground(new java.awt.Color(196, 179, 179));
        m2.setText("2.Mission");
        m2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                m2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                m2FocusLost(evt);
            }
        });
        m2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("To-Do List Mini App");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(m5)
                            .addComponent(m1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(m2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(m3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(m4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(d1)
                            .addComponent(d2)
                            .addComponent(d3)
                            .addComponent(d4)
                            .addComponent(d5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(124, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(c2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(c3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(c4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(c5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(c7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(c8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(c9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(c10, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(m1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(m2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(m3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(m4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(c4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(m5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(c5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(d3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(d4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(d5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(c6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(c7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(c8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(c9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(c10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void m2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m2ActionPerformed
        m1count++;
        if(m1count%2 == 0){
            m2.setSize(300, 120);
        }
        else if(m1count%2 != 0){
            m2.setSize(230,40);
        }
    }//GEN-LAST:event_m2ActionPerformed

    private void m4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m4ActionPerformed
       m1count++;
        if(m1count%2 == 0){
            m4.setSize(300, 120);
        }
        else if(m1count%2 != 0){
            m4.setSize(230,40);
        }
    }//GEN-LAST:event_m4ActionPerformed

    private void m3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m3ActionPerformed
        m1count++;
        if(m1count%2 == 0){
            m3.setSize(300, 120);
        }
        else if(m1count%2 != 0){
            m3.setSize(230,40);
        }
    }//GEN-LAST:event_m3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        for(int i=1;i<=5;i++){
            if(!m1.isVisible()){
                m1.setVisible(true);
                m1.setBackground(Color.white);
                m1.setText("1.Mission");
                m1.setForeground(Color.lightGray);
                d1.setVisible(true);
                c1.setVisible(true);
                break;
            }
            else if(m1.isVisible() && !m2.isVisible()){
                m2.setVisible(true);
                m2.setBackground(Color.white);
                m2.setText("2.Mission");
                m2.setForeground(Color.lightGray);
                d2.setVisible(true);
                c2.setVisible(true);
                break;
            }
            else if(m2.isVisible() && !m3.isVisible()){
                m3.setVisible(true);
                m3.setBackground(Color.white);
                m3.setText("3.Mission");
                m3.setForeground(Color.lightGray);
                d3.setVisible(true);
                c3.setVisible(true);
                break;
            }
            else if(m3.isVisible() && !m4.isVisible()){
                m4.setVisible(true);
                m4.setBackground(Color.white);
                m4.setText("4.Mission");
                m4.setForeground(Color.lightGray);
                d4.setVisible(true);
                c4.setVisible(true);
                break;
            }
            else if(m4.isVisible() && !m5.isVisible()){
                m5.setVisible(true);
                m5.setBackground(Color.white);
                m5.setText("5.Mission");
                m5.setForeground(Color.lightGray);
                d5.setVisible(true);
                c5.setVisible(true);
                break;
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed
    int m1count = 1;
    private void m1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m1ActionPerformed
        
        m1count++;
        if(m1count%2 == 0){
            m1.setSize(300, 120);
        }
        else if(m1count%2 != 0){
            m1.setSize(230,40);
        }
        
    }//GEN-LAST:event_m1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        m1.setBackground(Color.red);

    }//GEN-LAST:event_c1ActionPerformed

    private void d1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d1ActionPerformed
        m1.setBackground(Color.green);
    }//GEN-LAST:event_d1ActionPerformed

    private void c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5ActionPerformed
        m5.setBackground(Color.red);
    }//GEN-LAST:event_c5ActionPerformed

    private void d5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d5ActionPerformed
        m5.setBackground(Color.green);
    }//GEN-LAST:event_d5ActionPerformed

    private void c10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c10ActionPerformed
        c5.setVisible(false);
        d5.setVisible(false);
        m5.setVisible(false);
        m5.setText("");
    }//GEN-LAST:event_c10ActionPerformed

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
        m4.setBackground(Color.red);
    }//GEN-LAST:event_c4ActionPerformed

    private void c9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c9ActionPerformed
        c4.setVisible(false);
        d4.setVisible(false);
        m4.setVisible(false);
        m4.setText("");
    }//GEN-LAST:event_c9ActionPerformed

    private void d4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d4ActionPerformed
        m4.setBackground(Color.green);
    }//GEN-LAST:event_d4ActionPerformed

    private void c8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c8ActionPerformed
        c3.setVisible(false);
        d3.setVisible(false);
        m3.setVisible(false);
        m3.setText("");
    }//GEN-LAST:event_c8ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        m3.setBackground(Color.red);
    }//GEN-LAST:event_c3ActionPerformed

    private void c7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c7ActionPerformed
        c2.setVisible(false);
        d2.setVisible(false);
        m2.setVisible(false);
        m2.setText("");
    }//GEN-LAST:event_c7ActionPerformed

    private void d3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d3ActionPerformed
        m3.setBackground(Color.green);
    }//GEN-LAST:event_d3ActionPerformed

    private void c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c6ActionPerformed
        c1.setVisible(false);
        d1.setVisible(false);
        m1.setVisible(false);
        m1.setText("");
    }//GEN-LAST:event_c6ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        m2.setBackground(Color.red);
    }//GEN-LAST:event_c2ActionPerformed

    private void d2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d2ActionPerformed
        m2.setBackground(Color.green);
    }//GEN-LAST:event_d2ActionPerformed

    private void m5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m5ActionPerformed
        m1count++;
        if(m1count%2 == 0){
            m5.setSize(300, 120);
        }
        else if(m1count%2 != 0){
            m5.setSize(230,40);
        }
    }//GEN-LAST:event_m5ActionPerformed

    private void m1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m1FocusGained
            m1.setForeground(Color.black);
            if(m1.getText().equals("1.Mission")){
                m1.setText("");
            }
    }//GEN-LAST:event_m1FocusGained

    private void m1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m1FocusLost
        if(m1.getText().isEmpty()){
            m1.setText("1.Mission");
            m1.setForeground(Color.lightGray);
            m1.setSize(230,40);
        }
        
        
    }//GEN-LAST:event_m1FocusLost

    private void m2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m2FocusGained
         m2.setForeground(Color.black);
            if(m2.getText().equals("2.Mission")){
                m2.setText("");
            }
    }//GEN-LAST:event_m2FocusGained

    private void m2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m2FocusLost
        if(m2.getText().isEmpty()){
            m2.setText("2.Mission");
            m2.setForeground(Color.lightGray);
            m2.setSize(230,40);
        }
    }//GEN-LAST:event_m2FocusLost

    private void m3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m3FocusGained
        m3.setForeground(Color.black);
        if(m3.getText().equals("3.Mission")){
            m3.setText("");
        }
    }//GEN-LAST:event_m3FocusGained

    private void m3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m3FocusLost
         if(m3.getText().isEmpty()){
            m3.setText("3.Mission");
            m3.setForeground(Color.lightGray);
            m3.setSize(230,40);
        }
    }//GEN-LAST:event_m3FocusLost

    private void m4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m4FocusGained
         m4.setForeground(Color.black);
        if(m4.getText().equals("4.Mission")){
            m4.setText("");
        }
    }//GEN-LAST:event_m4FocusGained

    private void m4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m4FocusLost
        if(m4.getText().isEmpty()){
            m4.setText("4.Mission");
            m4.setForeground(Color.lightGray);
            m4.setSize(230,40);
        }
    }//GEN-LAST:event_m4FocusLost

    private void m5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m5FocusLost
       if(m5.getText().isEmpty()){
            m5.setText("5.Mission");
            m5.setForeground(Color.lightGray);
            m5.setSize(230,40);
        }
    }//GEN-LAST:event_m5FocusLost

    private void m5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m5FocusGained
         m5.setForeground(Color.black);
        if(m5.getText().equals("5.Mission")){
            m5.setText("");
        }
    }//GEN-LAST:event_m5FocusGained
                                 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(todolist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(todolist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(todolist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(todolist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new todolist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton c1;
    private javax.swing.JButton c10;
    private javax.swing.JButton c2;
    private javax.swing.JButton c3;
    private javax.swing.JButton c4;
    private javax.swing.JButton c5;
    private javax.swing.JButton c6;
    private javax.swing.JButton c7;
    private javax.swing.JButton c8;
    private javax.swing.JButton c9;
    private javax.swing.JButton d1;
    private javax.swing.JButton d2;
    private javax.swing.JButton d3;
    private javax.swing.JButton d4;
    private javax.swing.JButton d5;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField m1;
    private javax.swing.JTextField m2;
    private javax.swing.JTextField m3;
    private javax.swing.JTextField m4;
    private javax.swing.JTextField m5;
    // End of variables declaration//GEN-END:variables
}
