
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Panel;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author erhan
 */
public class filechooserandcolorchooser extends javax.swing.JFrame {

    /**
     * Creates new form filechooserandcolorchooser
     */
    public filechooserandcolorchooser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        openFolder = new javax.swing.JButton();
        changeColor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        writePlace = new javax.swing.JTextArea();
        clear = new javax.swing.JButton();
        darkMod = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.lightGray);
        setBounds(new java.awt.Rectangle(400, 200, 0, 0));

        openFolder.setText("Open Folder");
        openFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFolderActionPerformed(evt);
            }
        });

        changeColor.setText("Change Color");
        changeColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeColorActionPerformed(evt);
            }
        });

        writePlace.setColumns(20);
        writePlace.setRows(5);
        jScrollPane1.setViewportView(writePlace);

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        darkMod.setText("Dark Mod");
        darkMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darkModActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(openFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(changeColor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(darkMod, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openFolder)
                    .addComponent(changeColor)
                    .addComponent(clear)
                    .addComponent(darkMod))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFolderActionPerformed
        JFileChooser fc = new JFileChooser();
        int i = fc.showOpenDialog(this);     
        
        if(i == JFileChooser.APPROVE_OPTION){
            File file = fc.getSelectedFile();
            String text="";
            try(Scanner ss = new Scanner(new BufferedReader(new FileReader(file)))){
                while(ss.hasNextLine()){
                    text += ss.nextLine() + "\n";
                }
                writePlace.setText(text);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(filechooserandcolorchooser.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_openFolderActionPerformed

    private void changeColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeColorActionPerformed
        Color color = JColorChooser.showDialog(this, "Choose a color", Color.BLUE);
        writePlace.setForeground(color);
    }//GEN-LAST:event_changeColorActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        writePlace.setText("");
    }//GEN-LAST:event_clearActionPerformed
    int darkcount=1;
    private void darkModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darkModActionPerformed
        darkcount += 1;
        
        if(darkcount %2 == 0){
            writePlace.setBackground(Color.black);
            writePlace.setForeground(Color.white);
            
            getContentPane().setBackground(Color.black);
            clear.setBackground(Color.black);
            openFolder.setBackground(Color.black);
            changeColor.setBackground(Color.black);
            darkMod.setBackground(Color.black);
            
            clear.setForeground(Color.white);
            openFolder.setForeground(Color.white);
            changeColor.setForeground(Color.white);
            darkMod.setForeground(Color.white);
            
        }
        else{
            writePlace.setBackground(Color.white);
            writePlace.setForeground(Color.black);
            getContentPane().setBackground(Color.lightGray);
            
            clear.setBackground(Color.lightGray);
            openFolder.setBackground(Color.lightGray);
            changeColor.setBackground(Color.lightGray);
            darkMod.setBackground(Color.lightGray);
            
            clear.setForeground(Color.black);
            openFolder.setForeground(Color.black);
            changeColor.setForeground(Color.black);
            darkMod.setForeground(Color.black);
        }
    }//GEN-LAST:event_darkModActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(filechooserandcolorchooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(filechooserandcolorchooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(filechooserandcolorchooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(filechooserandcolorchooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new filechooserandcolorchooser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeColor;
    private javax.swing.JButton clear;
    private javax.swing.JButton darkMod;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton openFolder;
    private javax.swing.JTextArea writePlace;
    // End of variables declaration//GEN-END:variables
}
